import type { Operador, Proveedor, Ruta, Tarifa, Unidad, Viaje } from "./types";

/** Expediente en blanco: cada unidad del seed solo declara lo que difiere. */
const EXPEDIENTE_VACIO = {
  marca: "",
  modelo: "",
  anio: null,
  vin: "",
  color: "",
  polizaSeguro: "",
  vencimientoSeguro: null,
  verificacionVigente: false,
  verificacionVencimiento: null,
  fotos: [],
  documentos: [],
} satisfies Partial<Unidad>;

function unidad(u: Partial<Unidad> & Pick<Unidad, "id" | "economico" | "placas" | "tipo">): Unidad {
  return {
    capacidadTon: 0,
    estado: "disponible",
    activo: true,
    ...EXPEDIENTE_VACIO,
    ...u,
  };
}

export const unidadesSeed: Unidad[] = [
  unidad({ id: "u1", economico: "T-101", placas: "AB-472-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje", marca: "Kenworth", modelo: "T680", anio: 2021, color: "Blanco", vin: "1XKAD49X1MJ123456", polizaSeguro: "GNP-88213", vencimientoSeguro: "2026-11-30", verificacionVigente: true, verificacionVencimiento: "2027-02-15" }),
  unidad({ id: "u2", economico: "T-102", placas: "AB-518-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje", marca: "Freightliner", modelo: "Cascadia", anio: 2020, color: "Gris", vin: "3AKJHHDR4LSJ98765", polizaSeguro: "GNP-88214", vencimientoSeguro: "2026-09-10", verificacionVigente: true, verificacionVencimiento: "2026-10-01" }),
  unidad({ id: "u3", economico: "R-204", placas: "CD-991-LP", tipo: "Rabón", capacidadTon: 10, marca: "Hino", modelo: "268", anio: 2019, color: "Blanco", vin: "5PVNJ8JT7K4S22110", polizaSeguro: "QUAL-4471", vencimientoSeguro: "2026-08-30", verificacionVigente: false, verificacionVencimiento: "2026-01-15" }),
  unidad({ id: "u4", economico: "R-205", placas: "CD-014-LP", tipo: "Rabón", capacidadTon: 10, estado: "taller", marca: "Hino", modelo: "268", anio: 2018, color: "Azul", vin: "5PVNJ8JT2J4S22119", polizaSeguro: "QUAL-4472", vencimientoSeguro: "2026-12-05", verificacionVigente: true, verificacionVencimiento: "2027-01-20" }),
  unidad({ id: "u5", economico: "C-310", placas: "EF-663-MN", tipo: "Camioneta 3.5", capacidadTon: 3.5, marca: "Ford", modelo: "F-350", anio: 2022, color: "Rojo", vin: "1FTBF3B69NEA12345", polizaSeguro: "GNP-88215", vencimientoSeguro: "2027-03-01", verificacionVigente: true, verificacionVencimiento: "2027-03-01" }),
  unidad({ id: "u6", economico: "T-103", placas: "AB-770-XC", tipo: "Tractocamión", capacidadTon: 30, marca: "Kenworth", modelo: "T680", anio: 2023, color: "Negro", vin: "1XKAD49X8PJ654321", polizaSeguro: "GNP-88216", vencimientoSeguro: "2027-05-20", verificacionVigente: true, verificacionVencimiento: "2027-06-01" }),
];

export const operadoresSeed: Operador[] = [
  { id: "o1", nombre: "Javier Robles", licencia: "E-4471203", celular: "55 1244 8890", rfc: "ROBJ850312H12", contactoEmergencia: "María Robles · 55 8820 1177", nss: "12345678901", estado: "en_viaje", activo: true },
  { id: "o2", nombre: "Marisol Aguilar", licencia: "E-3390118", celular: "55 8871 2033", rfc: "AUGM900722M45", contactoEmergencia: "Pedro Aguilar · 55 3341 9902", nss: "23456789012", estado: "en_viaje", activo: true },
  { id: "o3", nombre: "Ernesto Padilla", licencia: "B-1120994", celular: "81 2255 7741", rfc: "PAEE880204H78", contactoEmergencia: "Lucía Padilla · 81 1120 4456", nss: "34567890123", estado: "disponible", activo: true },
  { id: "o4", nombre: "Luis Fernando Cruz", licencia: "E-5583321", celular: "33 4410 9902", rfc: "CULF920918H23", contactoEmergencia: "Diana Cruz · 33 7789 0021", nss: "45678901234", estado: "descanso", activo: true },
  { id: "o5", nombre: "Ana Karen Ibarra", licencia: "B-7741220", celular: "55 3390 1188", rfc: "IAAK950630M67", contactoEmergencia: "Roberto Ibarra · 55 2290 3345", nss: "56789012345", estado: "disponible", activo: true },
];

export const proveedoresSeed: Proveedor[] = [
  { id: "p1", nombre: "Fletes del Golfo", tipo: "transportista", diasPago: 30, contacto: "operaciones@fletesdelgolfo.mx", activo: true },
  { id: "p2", nombre: "Autotransportes Bajío", tipo: "transportista", diasPago: 45, contacto: "trafico@atbajio.mx", activo: true },
  { id: "p3", nombre: "Aduanal Terán y Asoc.", tipo: "agente_aduanal", diasPago: 15, contacto: "despacho@teran.mx", activo: true },
  { id: "p4", nombre: "Almacenes Pacífico", tipo: "almacen", diasPago: 30, contacto: "contacto@almpacifico.mx", activo: true },
];

export const tarifasSeed: Tarifa[] = [
  { id: "tf1", clienteId: "c1", cliente: "Grupo Ferretero del Norte", origen: "CDMX", destino: "Monterrey", tarifaVenta: 48500, activo: true },
  { id: "tf2", clienteId: "c1", cliente: "Grupo Ferretero del Norte", origen: "CDMX", destino: "Querétaro", tarifaVenta: 14300, activo: true },
  { id: "tf3", clienteId: "c2", cliente: "Alimentos La Huerta", origen: "Guadalajara", destino: "CDMX", tarifaVenta: 31200, activo: true },
  { id: "tf4", clienteId: "c2", cliente: "Alimentos La Huerta", origen: "CDMX", destino: "Veracruz", tarifaVenta: 22400, activo: true },
  { id: "tf5", clienteId: "c3", cliente: "Distribuidora Peninsular", origen: "CDMX", destino: "Puebla", tarifaVenta: 9800, activo: true },
  { id: "tf6", clienteId: "c3", cliente: "Distribuidora Peninsular", origen: "Mérida", destino: "Cancún", tarifaVenta: 24500, activo: true },
  { id: "tf7", clienteId: "c4", cliente: "Cementos del Bajío", origen: "Querétaro", destino: "León", tarifaVenta: 12750, activo: true },
  { id: "tf8", clienteId: "c5", cliente: "Comercializadora Andina", origen: "Manzanillo", destino: "CDMX", tarifaVenta: 58900, activo: true },
  { id: "tf9", clienteId: "c5", cliente: "Comercializadora Andina", origen: "Veracruz", destino: "Querétaro", tarifaVenta: 41800, activo: true },
  { id: "tf10", clienteId: "c6", cliente: "Textiles del Valle", origen: "Laredo", destino: "Puebla", tarifaVenta: 76400, activo: true },
];

export const rutasSeed: Ruta[] = [
  { id: "rt1", codigo: "CDMX-MTY", origen: "CDMX", destino: "Monterrey", kmProyectados: 900, casetasProyectadas: 1250, activo: true },
  { id: "rt2", codigo: "GDL-CDMX", origen: "Guadalajara", destino: "CDMX", kmProyectados: 550, casetasProyectadas: 780, activo: true },
  { id: "rt3", codigo: "CDMX-PUE", origen: "CDMX", destino: "Puebla", kmProyectados: 135, casetasProyectadas: 210, activo: true },
  { id: "rt4", codigo: "CDMX-QRO", origen: "CDMX", destino: "Querétaro", kmProyectados: 215, casetasProyectadas: 320, activo: true },
  { id: "rt5", codigo: "QRO-LEO", origen: "Querétaro", destino: "León", kmProyectados: 190, casetasProyectadas: 260, activo: true },
];

/** Monitoreo en blanco: cada entrada del seed solo declara lo que difiere. */
const MONITOREO_VACIO: Viaje["monitoreo"] = {
  avance: 0,
  ubicacion: "—",
  ultimoEvento: "Servicio dado de alta",
  actualizado: "2026-08-15T08:00:00Z",
  operadorManual: "",
  medioComunicacion: "",
  unidadManual: "",
  placaManual: "",
  observaciones: "",
  cuentaEspejo: "",
  referencia: "",
  salidaPatio: "",
  arriboCarga: "",
  ingresoCargar: "",
  inicioRuta: "",
  arriboDestino: "",
  ingresoDescarga: "",
  servicioFinalizado: "",
};

/**
 * Base de un servicio. Cada registro del seed solo declara lo que lo hace
 * distinto; así los 10 servicios de ejemplo caben sin repetir 30 campos. El
 * bloque de monitoreo se combina campo a campo, no se reemplaza entero, para
 * no tener que repetir los diez y tantos campos que no cambian.
 */
function servicio(
  v: Partial<Omit<Viaje, "monitoreo" | "costos">> &
    Pick<Viaje, "id" | "folio" | "cliente"> & {
      monitoreo?: Partial<Viaje["monitoreo"]>;
      costos?: Partial<Viaje["costos"]>;
    },
): Viaje {
  // El desglose manda: el total siempre es su suma, igual que en el backend.
  // Lo que un registro declare como `costo` sin desglosar se atribuye al
  // proveedor en FWD y a "otros" en TDC, que es donde semánticamente cae.
  const costos: Viaje["costos"] = {
    proveedor: 0,
    combustible: 0,
    casetas: 0,
    operador: 0,
    otros: 0,
    ...(v.costos ??
      (v.costo
        ? v.asignacion === "FWD"
          ? { proveedor: v.costo }
          : { otros: v.costo }
        : {})),
  };

  return {
    cartaPorte: `CP-2026-${v.folio.replace(/\D/g, "")}`,
    clienteId: "",
    origen: "CDMX",
    destino: "Monterrey",
    puertoId: "pt8",
    citaCarga: "2026-08-15T08:00",
    citaDescarga: "2026-08-16T14:00",
    asignacion: "TDC",
    unidadId: "",
    operadorId: "",
    proveedorId: "",
    rutaId: "",
    rutaCodigo: "",
    tipoNegocioId: "tn5",
    temperatura: "SECO",
    modalidad: "RT",
    tipoUnidadId: "tu2",
    tipoMercanciaId: "tm1",
    contenedor1: "",
    contenedor2: "",
    booking: "",
    po: "",
    estado: "programado",
    km: 0,
    casetasProyectadas: 0,
    tarifa: 0,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 30 },
    pago: { estado: "pendiente", referencia: null, fechaPago: null },
    liquidacion: {
      estado: "pendiente",
      fecha: null,
      combustible: 0,
      casetas: 0,
      gastosExtra: 0,
      gastosExtraDetalle: null,
      evidencias: false,
    },
    ...v,
    costos,
    costo: Object.values(costos).reduce((suma, parte) => suma + parte, 0),
    monitoreo: { ...MONITOREO_VACIO, ...v.monitoreo },
  };
}

export const viajesSeed: Viaje[] = [
  servicio({
    id: "v1",
    folio: "RT-2601",
    clienteId: "c1",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Monterrey",
    puertoId: "pt8",
    citaCarga: "2026-08-12T07:30",
    citaDescarga: "2026-08-13T16:00",
    estado: "en_ruta_vuelta",
    km: 900,
    casetasProyectadas: 1250,
    asignacion: "TDC",
    unidadId: "u1",
    operadorId: "o1",
    rutaId: "rt1",
    rutaCodigo: "CDMX-MTY",
    tipoNegocioId: "tn1",
    tipoUnidadId: "tu3",
    tipoMercanciaId: "tm7",
    contenedor1: "MSCU-4471203",
    contenedor2: "MSCU-4471204",
    po: "PO-88231",
    tarifa: 48500,
    costos: { proveedor: 0, combustible: 18200, casetas: 6400, operador: 5300, otros: 1500 },
    monitoreo: {
      avance: 78,
      ubicacion: "Saltillo, Coahuila",
      ultimoEvento: "Salida de Apodaca con carga de compensación",
      actualizado: "2026-08-15T14:20:00Z",
      operadorManual: "Javier Robles",
      medioComunicacion: "Celular 55 1244 8890",
      unidadManual: "T-101",
      placaManual: "AB-472-XC",
      observaciones: "Retorno con carga de compensación desde Apodaca.",
      referencia: "MON-88231",
      salidaPatio: "2026-08-12T07:15",
      arriboCarga: "2026-08-12T08:10",
      ingresoCargar: "2026-08-12T08:30",
      inicioRuta: "2026-08-12T10:05",
      arriboDestino: "2026-08-13T09:40",
    },
    notas: "Retorno con carga de compensación desde Apodaca.",
  }),
  servicio({
    id: "v2",
    folio: "RT-2602",
    clienteId: "c2",
    cliente: "Alimentos La Huerta",
    origen: "Guadalajara",
    destino: "CDMX",
    citaCarga: "2026-08-14T06:00",
    citaDescarga: "2026-08-15T09:00",
    estado: "en_ruta_ida",
    km: 1140,
    asignacion: "TDC",
    unidadId: "u2",
    operadorId: "o2",
    tipoNegocioId: "tn4",
    temperatura: "RF",
    tipoUnidadId: "tu2",
    tipoMercanciaId: "tm2",
    po: "PO-88250",
    tarifa: 31200,
    costo: 20800,
    monitoreo: {
      avance: 35,
      ubicacion: "La Piedad, Michoacán",
      ultimoEvento: "Paso por caseta Zapotlanejo",
      actualizado: "2026-08-15T11:05:00Z",
      operadorManual: "Marisol Aguilar",
      medioComunicacion: "Radio flotilla canal 4",
      unidadManual: "T-102",
      placaManual: "AB-518-XC",
      referencia: "MON-88250",
      salidaPatio: "2026-08-14T05:45",
      arriboCarga: "2026-08-14T06:30",
      ingresoCargar: "2026-08-14T06:50",
      inicioRuta: "2026-08-14T08:15",
    },
  }),
  servicio({
    id: "v3",
    folio: "RT-2603",
    clienteId: "c3",
    cliente: "Distribuidora Peninsular",
    origen: "CDMX",
    destino: "Puebla",
    citaCarga: "2026-08-15T09:00",
    citaDescarga: "2026-08-15T15:00",
    estado: "por_asignar",
    km: 270,
    asignacion: "TDC",
    unidadId: "",
    operadorId: "",
    tipoNegocioId: "tn4",
    tipoUnidadId: "tu6",
    tipoMercanciaId: "tm1",
    tarifa: 9800,
    costo: 6100,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 15 },
    monitoreo: {
      avance: 0,
      ubicacion: "—",
      ultimoEvento: "Servicio dado de alta, pendiente de asignar unidad",
      actualizado: "2026-08-15T08:00:00Z",
      operadorManual: "",
      medioComunicacion: "",
      unidadManual: "",
      placaManual: "",
    },
    notas: "Mismo día, ida y vuelta.",
  }),
  servicio({
    id: "v4",
    folio: "RT-2598",
    clienteId: "c1",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Querétaro",
    citaCarga: "2026-08-04T08:00",
    citaDescarga: "2026-08-04T18:00",
    estado: "completado",
    km: 430,
    asignacion: "TDC",
    unidadId: "u6",
    operadorId: "o5",
    tipoNegocioId: "tn5",
    tipoUnidadId: "tu1",
    tipoMercanciaId: "tm7",
    tarifa: 14300,
    costo: 8900,
    // Cerrado pero aún sin facturar: es el caso que abre el flujo de CXC.
    monitoreo: {
      avance: 100,
      ubicacion: "Patio CDMX",
      ultimoEvento: "Retorno confirmado y evidencia cargada",
      actualizado: "2026-08-06T18:40:00Z",
      operadorManual: "Ana Karen Ibarra",
      medioComunicacion: "Celular 55 3390 1188",
      unidadManual: "T-103",
      placaManual: "AB-770-XC",
    },
  }),
  servicio({
    id: "v5",
    folio: "RT-2599",
    clienteId: "c4",
    cliente: "Cementos del Bajío",
    origen: "Querétaro",
    destino: "León",
    citaCarga: "2026-08-07T07:00",
    citaDescarga: "2026-08-08T12:00",
    estado: "completado",
    km: 380,
    asignacion: "TDC",
    unidadId: "u1",
    operadorId: "o1",
    tipoNegocioId: "tn5",
    tipoUnidadId: "tu1",
    tipoMercanciaId: "tm7",
    tarifa: 12750,
    costos: { proveedor: 0, combustible: 4600, casetas: 1900, operador: 1100, otros: 300 },
    cobro: { estado: "cobrado", factura: "A-10430", fechaFactura: "2026-07-28", diasCredito: 30 },
    pago: { estado: "pagado", referencia: "SPEI-88213", fechaPago: "2026-08-11" },
    liquidacion: { estado: "liquidado", fecha: "2026-08-12", combustible: 0, casetas: 0, gastosExtra: 0, gastosExtraDetalle: null, evidencias: true },
    monitoreo: {
      avance: 100,
      ubicacion: "Patio Querétaro",
      ultimoEvento: "Servicio cerrado",
      actualizado: "2026-08-09T17:10:00Z",
      operadorManual: "Javier Robles",
      medioComunicacion: "Celular 55 1244 8890",
      unidadManual: "T-101",
      placaManual: "AB-472-XC",
    },
  }),
  servicio({
    id: "v6",
    folio: "RT-2600",
    clienteId: "c2",
    cliente: "Alimentos La Huerta",
    origen: "CDMX",
    destino: "Veracruz",
    puertoId: "pt3",
    citaCarga: "2026-08-09T06:00",
    citaDescarga: "2026-08-10T10:00",
    estado: "cancelado",
    km: 810,
    asignacion: "TDC",
    unidadId: "u5",
    operadorId: "o4",
    tipoNegocioId: "tn2",
    temperatura: "RF",
    tipoUnidadId: "tu7",
    tipoMercanciaId: "tm2",
    tarifa: 22400,
    costo: 0,
    monitoreo: {
      avance: 0,
      ubicacion: "—",
      ultimoEvento: "Cliente reprogramó el embarque",
      actualizado: "2026-08-08T09:30:00Z",
      operadorManual: "",
      medioComunicacion: "",
      unidadManual: "",
      placaManual: "",
    },
    notas: "Cliente reprogramó el embarque.",
  }),

  // ---- Servicios cubiertos con proveedor externo (FWD) ----
  servicio({
    id: "v7",
    folio: "RT-2604",
    clienteId: "c5",
    cliente: "Comercializadora Andina",
    origen: "Manzanillo",
    destino: "CDMX",
    puertoId: "pt1",
    citaCarga: "2026-08-13T05:00",
    citaDescarga: "2026-08-14T11:00",
    estado: "en_ruta_ida",
    km: 1560,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p1",
    tipoNegocioId: "tn3",
    tipoUnidadId: "tu4",
    tipoMercanciaId: "tm5",
    contenedor1: "TCLU-7783120",
    booking: "BKG-556201",
    po: "PO-77120",
    tarifa: 58900,
    costo: 44200,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 45 },
    monitoreo: {
      avance: 42,
      ubicacion: "Guadalajara, Jalisco",
      ultimoEvento: "Reporte del proveedor: en tránsito sin novedad",
      actualizado: "2026-08-15T10:15:00Z",
      operadorManual: "Ramiro Solís (Fletes del Golfo)",
      medioComunicacion: "WhatsApp 33 1188 4420",
      unidadManual: "FDG-118",
      placaManual: "JC-227-45",
      cuentaEspejo: "GPS-FDG-8821",
      referencia: "MON-77120",
      salidaPatio: "2026-08-13T04:40",
      arriboCarga: "2026-08-13T05:20",
      ingresoCargar: "2026-08-13T06:00",
      inicioRuta: "2026-08-13T07:10",
    },
    notas: "Importación con despacho en Manzanillo.",
  }),
  servicio({
    id: "v8",
    folio: "RT-2605",
    clienteId: "c6",
    cliente: "Textiles del Valle",
    origen: "Laredo",
    destino: "Puebla",
    puertoId: "pt7",
    citaCarga: "2026-08-10T04:30",
    citaDescarga: "2026-08-12T13:00",
    estado: "completado",
    km: 2080,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p2",
    tipoNegocioId: "tn6",
    tipoUnidadId: "tu5",
    tipoMercanciaId: "tm6",
    contenedor1: "HLXU-2214508",
    contenedor2: "HLXU-2214509",
    booking: "BKG-559880",
    po: "PO-77340",
    tarifa: 76400,
    costo: 61300,
    cobro: { estado: "facturado", factura: "A-10451", fechaFactura: "2026-08-14", diasCredito: 45 },
    pago: { estado: "autorizado", referencia: null, fechaPago: null },
    monitoreo: {
      avance: 100,
      ubicacion: "Puebla, Puebla",
      ultimoEvento: "Entrega confirmada con sello del cliente",
      actualizado: "2026-08-14T16:25:00Z",
      operadorManual: "Héctor Villanueva (Autotransportes Bajío)",
      medioComunicacion: "Celular 33 5521 0087",
      unidadManual: "ATB-054",
      placaManual: "GJ-340-12",
      cuentaEspejo: "GPS-ATB-3390",
      referencia: "MON-77340",
      salidaPatio: "2026-08-10T04:00",
      arriboCarga: "2026-08-10T04:45",
      ingresoCargar: "2026-08-10T05:15",
      inicioRuta: "2026-08-10T06:30",
      arriboDestino: "2026-08-12T10:50",
      ingresoDescarga: "2026-08-12T11:30",
      servicioFinalizado: "2026-08-12T13:00",
    },
  }),
  servicio({
    id: "v9",
    folio: "RT-2596",
    clienteId: "c5",
    cliente: "Comercializadora Andina",
    origen: "Veracruz",
    destino: "Querétaro",
    puertoId: "pt3",
    citaCarga: "2026-06-22T06:00",
    citaDescarga: "2026-06-24T12:00",
    estado: "completado",
    km: 1120,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p1",
    tipoNegocioId: "tn3",
    tipoUnidadId: "tu4",
    tipoMercanciaId: "tm5",
    contenedor1: "MEDU-9981204",
    booking: "BKG-548803",
    tarifa: 41800,
    costo: 32600,
    // Facturado hace tiempo y aún sin cobrar: cae en vencido.
    cobro: { estado: "vencido", factura: "A-10388", fechaFactura: "2026-06-26", diasCredito: 30 },
    pago: { estado: "pagado", referencia: "SPEI-87004", fechaPago: "2026-07-20" },
    liquidacion: { estado: "liquidado", fecha: "2026-07-01", combustible: 0, casetas: 0, gastosExtra: 0, gastosExtraDetalle: null, evidencias: true },
    monitoreo: {
      avance: 100,
      ubicacion: "Querétaro, Querétaro",
      ultimoEvento: "Servicio cerrado",
      actualizado: "2026-06-25T19:00:00Z",
      operadorManual: "Ramiro Solís (Fletes del Golfo)",
      medioComunicacion: "WhatsApp 33 1188 4420",
      unidadManual: "FDG-102",
      placaManual: "JC-118-90",
    },
  }),
  servicio({
    id: "v10",
    folio: "RT-2606",
    clienteId: "c3",
    cliente: "Distribuidora Peninsular",
    origen: "Mérida",
    destino: "Cancún",
    puertoId: "pt6",
    citaCarga: "2026-08-16T07:00",
    citaDescarga: "2026-08-16T15:00",
    estado: "por_asignar",
    km: 640,
    asignacion: "FWD",
    proveedorId: "",
    tipoNegocioId: "tn4",
    tipoUnidadId: "tu6",
    tipoMercanciaId: "tm1",
    tarifa: 24500,
    costo: 18900,
    monitoreo: {
      avance: 0,
      ubicacion: "—",
      ultimoEvento: "Servicio dado de alta, pendiente de asignar proveedor",
      actualizado: "2026-08-15T09:45:00Z",
      operadorManual: "",
      medioComunicacion: "",
      unidadManual: "",
      placaManual: "",
    },
  }),
];
