import type { Operador, Proveedor, Unidad, Viaje } from "./types";

export const unidadesSeed: Unidad[] = [
  { id: "u1", economico: "T-101", placas: "AB-472-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje", activo: true },
  { id: "u2", economico: "T-102", placas: "AB-518-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje", activo: true },
  { id: "u3", economico: "R-204", placas: "CD-991-LP", tipo: "Rabón", capacidadTon: 10, estado: "disponible", activo: true },
  { id: "u4", economico: "R-205", placas: "CD-014-LP", tipo: "Rabón", capacidadTon: 10, estado: "taller", activo: true },
  { id: "u5", economico: "C-310", placas: "EF-663-MN", tipo: "Camioneta 3.5", capacidadTon: 3.5, estado: "disponible", activo: true },
  { id: "u6", economico: "T-103", placas: "AB-770-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "disponible", activo: true },
];

export const operadoresSeed: Operador[] = [
  { id: "o1", nombre: "Javier Robles", licencia: "E-4471203", telefono: "55 1244 8890", estado: "en_viaje", activo: true },
  { id: "o2", nombre: "Marisol Aguilar", licencia: "E-3390118", telefono: "55 8871 2033", estado: "en_viaje", activo: true },
  { id: "o3", nombre: "Ernesto Padilla", licencia: "B-1120994", telefono: "81 2255 7741", estado: "disponible", activo: true },
  { id: "o4", nombre: "Luis Fernando Cruz", licencia: "E-5583321", telefono: "33 4410 9902", estado: "descanso", activo: true },
  { id: "o5", nombre: "Ana Karen Ibarra", licencia: "B-7741220", telefono: "55 3390 1188", estado: "disponible", activo: true },
];

export const proveedoresSeed: Proveedor[] = [
  { id: "p1", nombre: "Fletes del Golfo", tipo: "transportista", diasPago: 30, contacto: "operaciones@fletesdelgolfo.mx", activo: true },
  { id: "p2", nombre: "Autotransportes Bajío", tipo: "transportista", diasPago: 45, contacto: "trafico@atbajio.mx", activo: true },
  { id: "p3", nombre: "Aduanal Terán y Asoc.", tipo: "agente_aduanal", diasPago: 15, contacto: "despacho@teran.mx", activo: true },
  { id: "p4", nombre: "Almacenes Pacífico", tipo: "almacen", diasPago: 30, contacto: "contacto@almpacifico.mx", activo: true },
];

/**
 * Base de un servicio. Cada registro del seed solo declara lo que lo hace
 * distinto; así los 10 servicios de ejemplo caben sin repetir 30 campos.
 */
function servicio(v: Partial<Viaje> & Pick<Viaje, "id" | "folio" | "cliente">): Viaje {
  return {
    cartaPorte: `CP-2026-${v.folio.replace(/\D/g, "")}`,
    clienteId: "",
    origen: "CDMX",
    destino: "Monterrey",
    puertoId: "pt8",
    citaCarga: "2026-08-15T08:00",
    citaDescarga: "2026-08-16T14:00",
    asignacion: "TDC",
    unidadId: "",
    operadorId: "",
    proveedorId: "",
    tipoNegocioId: "tn5",
    temperatura: "SECO",
    modalidad: "RT",
    tipoUnidadId: "tu2",
    tipoMercanciaId: "tm1",
    contenedor1: "",
    contenedor2: "",
    booking: "",
    po: "",
    estado: "programado",
    km: 0,
    tarifa: 0,
    costo: 0,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 30 },
    pago: { estado: "pendiente", referencia: null, fechaPago: null },
    liquidacion: { estado: "pendiente", fecha: null },
    monitoreo: {
      avance: 0,
      ubicacion: "—",
      ultimoEvento: "Servicio dado de alta",
      actualizado: "2026-08-15T08:00:00Z",
    },
    ...v,
  };
}

export const viajesSeed: Viaje[] = [
  servicio({
    id: "v1",
    folio: "RT-2601",
    clienteId: "c1",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Monterrey",
    puertoId: "pt8",
    citaCarga: "2026-08-12T07:30",
    citaDescarga: "2026-08-13T16:00",
    estado: "en_ruta_vuelta",
    km: 1720,
    asignacion: "TDC",
    unidadId: "u1",
    operadorId: "o1",
    tipoNegocioId: "tn1",
    tipoUnidadId: "tu3",
    tipoMercanciaId: "tm7",
    contenedor1: "MSCU-4471203",
    contenedor2: "MSCU-4471204",
    po: "PO-88231",
    tarifa: 48500,
    costo: 31400,
    monitoreo: {
      avance: 78,
      ubicacion: "Saltillo, Coahuila",
      ultimoEvento: "Salida de Apodaca con carga de compensación",
      actualizado: "2026-08-15T14:20:00Z",
    },
    notas: "Retorno con carga de compensación desde Apodaca.",
  }),
  servicio({
    id: "v2",
    folio: "RT-2602",
    clienteId: "c2",
    cliente: "Alimentos La Huerta",
    origen: "Guadalajara",
    destino: "CDMX",
    citaCarga: "2026-08-14T06:00",
    citaDescarga: "2026-08-15T09:00",
    estado: "en_ruta_ida",
    km: 1140,
    asignacion: "TDC",
    unidadId: "u2",
    operadorId: "o2",
    tipoNegocioId: "tn4",
    temperatura: "RF",
    tipoUnidadId: "tu2",
    tipoMercanciaId: "tm2",
    po: "PO-88250",
    tarifa: 31200,
    costo: 20800,
    monitoreo: {
      avance: 35,
      ubicacion: "La Piedad, Michoacán",
      ultimoEvento: "Paso por caseta Zapotlanejo",
      actualizado: "2026-08-15T11:05:00Z",
    },
  }),
  servicio({
    id: "v3",
    folio: "RT-2603",
    clienteId: "c3",
    cliente: "Distribuidora Peninsular",
    origen: "CDMX",
    destino: "Puebla",
    citaCarga: "2026-08-15T09:00",
    citaDescarga: "2026-08-15T15:00",
    estado: "programado",
    km: 270,
    asignacion: "TDC",
    unidadId: "u3",
    operadorId: "o3",
    tipoNegocioId: "tn4",
    tipoUnidadId: "tu6",
    tipoMercanciaId: "tm1",
    tarifa: 9800,
    costo: 6100,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 15 },
    monitoreo: {
      avance: 0,
      ubicacion: "Patio CDMX",
      ultimoEvento: "Unidad asignada, pendiente de carga",
      actualizado: "2026-08-15T08:00:00Z",
    },
    notas: "Mismo día, ida y vuelta.",
  }),
  servicio({
    id: "v4",
    folio: "RT-2598",
    clienteId: "c1",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Querétaro",
    citaCarga: "2026-08-04T08:00",
    citaDescarga: "2026-08-04T18:00",
    estado: "completado",
    km: 430,
    asignacion: "TDC",
    unidadId: "u6",
    operadorId: "o5",
    tipoNegocioId: "tn5",
    tipoUnidadId: "tu1",
    tipoMercanciaId: "tm7",
    tarifa: 14300,
    costo: 8900,
    // Cerrado pero aún sin facturar: es el caso que abre el flujo de CXC.
    monitoreo: {
      avance: 100,
      ubicacion: "Patio CDMX",
      ultimoEvento: "Retorno confirmado y evidencia cargada",
      actualizado: "2026-08-06T18:40:00Z",
    },
  }),
  servicio({
    id: "v5",
    folio: "RT-2599",
    clienteId: "c4",
    cliente: "Cementos del Bajío",
    origen: "Querétaro",
    destino: "León",
    citaCarga: "2026-08-07T07:00",
    citaDescarga: "2026-08-08T12:00",
    estado: "completado",
    km: 380,
    asignacion: "TDC",
    unidadId: "u1",
    operadorId: "o1",
    tipoNegocioId: "tn5",
    tipoUnidadId: "tu1",
    tipoMercanciaId: "tm7",
    tarifa: 12750,
    costo: 7900,
    cobro: { estado: "cobrado", factura: "A-10430", fechaFactura: "2026-07-28", diasCredito: 30 },
    pago: { estado: "pagado", referencia: "SPEI-88213", fechaPago: "2026-08-11" },
    liquidacion: { estado: "liquidado", fecha: "2026-08-12" },
    monitoreo: {
      avance: 100,
      ubicacion: "Patio Querétaro",
      ultimoEvento: "Servicio cerrado",
      actualizado: "2026-08-09T17:10:00Z",
    },
  }),
  servicio({
    id: "v6",
    folio: "RT-2600",
    clienteId: "c2",
    cliente: "Alimentos La Huerta",
    origen: "CDMX",
    destino: "Veracruz",
    puertoId: "pt3",
    citaCarga: "2026-08-09T06:00",
    citaDescarga: "2026-08-10T10:00",
    estado: "cancelado",
    km: 810,
    asignacion: "TDC",
    unidadId: "u5",
    operadorId: "o4",
    tipoNegocioId: "tn2",
    temperatura: "RF",
    tipoUnidadId: "tu7",
    tipoMercanciaId: "tm2",
    tarifa: 22400,
    costo: 0,
    monitoreo: {
      avance: 0,
      ubicacion: "—",
      ultimoEvento: "Cliente reprogramó el embarque",
      actualizado: "2026-08-08T09:30:00Z",
    },
    notas: "Cliente reprogramó el embarque.",
  }),

  // ---- Servicios cubiertos con proveedor externo (FWD) ----
  servicio({
    id: "v7",
    folio: "RT-2604",
    clienteId: "c5",
    cliente: "Comercializadora Andina",
    origen: "Manzanillo",
    destino: "CDMX",
    puertoId: "pt1",
    citaCarga: "2026-08-13T05:00",
    citaDescarga: "2026-08-14T11:00",
    estado: "en_ruta_ida",
    km: 1560,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p1",
    tipoNegocioId: "tn3",
    tipoUnidadId: "tu4",
    tipoMercanciaId: "tm5",
    contenedor1: "TCLU-7783120",
    booking: "BKG-556201",
    po: "PO-77120",
    tarifa: 58900,
    costo: 44200,
    cobro: { estado: "pendiente", factura: null, fechaFactura: null, diasCredito: 45 },
    monitoreo: {
      avance: 42,
      ubicacion: "Guadalajara, Jalisco",
      ultimoEvento: "Reporte del proveedor: en tránsito sin novedad",
      actualizado: "2026-08-15T10:15:00Z",
    },
    notas: "Importación con despacho en Manzanillo.",
  }),
  servicio({
    id: "v8",
    folio: "RT-2605",
    clienteId: "c6",
    cliente: "Textiles del Valle",
    origen: "Laredo",
    destino: "Puebla",
    puertoId: "pt7",
    citaCarga: "2026-08-10T04:30",
    citaDescarga: "2026-08-12T13:00",
    estado: "completado",
    km: 2080,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p2",
    tipoNegocioId: "tn6",
    tipoUnidadId: "tu5",
    tipoMercanciaId: "tm6",
    contenedor1: "HLXU-2214508",
    contenedor2: "HLXU-2214509",
    booking: "BKG-559880",
    po: "PO-77340",
    tarifa: 76400,
    costo: 61300,
    cobro: { estado: "facturado", factura: "A-10451", fechaFactura: "2026-08-14", diasCredito: 45 },
    pago: { estado: "autorizado", referencia: null, fechaPago: null },
    monitoreo: {
      avance: 100,
      ubicacion: "Puebla, Puebla",
      ultimoEvento: "Entrega confirmada con sello del cliente",
      actualizado: "2026-08-14T16:25:00Z",
    },
  }),
  servicio({
    id: "v9",
    folio: "RT-2596",
    clienteId: "c5",
    cliente: "Comercializadora Andina",
    origen: "Veracruz",
    destino: "Querétaro",
    puertoId: "pt3",
    citaCarga: "2026-06-22T06:00",
    citaDescarga: "2026-06-24T12:00",
    estado: "completado",
    km: 1120,
    modalidad: "OW",
    asignacion: "FWD",
    proveedorId: "p1",
    tipoNegocioId: "tn3",
    tipoUnidadId: "tu4",
    tipoMercanciaId: "tm5",
    contenedor1: "MEDU-9981204",
    booking: "BKG-548803",
    tarifa: 41800,
    costo: 32600,
    // Facturado hace tiempo y aún sin cobrar: cae en vencido.
    cobro: { estado: "vencido", factura: "A-10388", fechaFactura: "2026-06-26", diasCredito: 30 },
    pago: { estado: "pagado", referencia: "SPEI-87004", fechaPago: "2026-07-20" },
    liquidacion: { estado: "liquidado", fecha: "2026-07-01" },
    monitoreo: {
      avance: 100,
      ubicacion: "Querétaro, Querétaro",
      ultimoEvento: "Servicio cerrado",
      actualizado: "2026-06-25T19:00:00Z",
    },
  }),
  servicio({
    id: "v10",
    folio: "RT-2606",
    clienteId: "c3",
    cliente: "Distribuidora Peninsular",
    origen: "Mérida",
    destino: "Cancún",
    puertoId: "pt6",
    citaCarga: "2026-08-16T07:00",
    citaDescarga: "2026-08-16T15:00",
    estado: "programado",
    km: 640,
    asignacion: "FWD",
    proveedorId: "p2",
    tipoNegocioId: "tn4",
    tipoUnidadId: "tu6",
    tipoMercanciaId: "tm1",
    tarifa: 24500,
    costo: 18900,
    monitoreo: {
      avance: 0,
      ubicacion: "Mérida, Yucatán",
      ultimoEvento: "Proveedor confirmó disponibilidad de unidad",
      actualizado: "2026-08-15T09:45:00Z",
    },
  }),
];
