import type { Operador, Unidad, Viaje } from "./types";

export const unidadesSeed: Unidad[] = [
  { id: "u1", economico: "T-101", placas: "AB-472-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje" },
  { id: "u2", economico: "T-102", placas: "AB-518-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "en_viaje" },
  { id: "u3", economico: "R-204", placas: "CD-991-LP", tipo: "Rabón", capacidadTon: 10, estado: "disponible" },
  { id: "u4", economico: "R-205", placas: "CD-014-LP", tipo: "Rabón", capacidadTon: 10, estado: "taller" },
  { id: "u5", economico: "C-310", placas: "EF-663-MN", tipo: "Camioneta 3.5", capacidadTon: 3.5, estado: "disponible" },
  { id: "u6", economico: "T-103", placas: "AB-770-XC", tipo: "Tractocamión", capacidadTon: 30, estado: "disponible" },
];

export const operadoresSeed: Operador[] = [
  { id: "o1", nombre: "Javier Robles", licencia: "E-4471203", telefono: "55 1244 8890", estado: "en_viaje" },
  { id: "o2", nombre: "Marisol Aguilar", licencia: "E-3390118", telefono: "55 8871 2033", estado: "en_viaje" },
  { id: "o3", nombre: "Ernesto Padilla", licencia: "B-1120994", telefono: "81 2255 7741", estado: "disponible" },
  { id: "o4", nombre: "Luis Fernando Cruz", licencia: "E-5583321", telefono: "33 4410 9902", estado: "descanso" },
  { id: "o5", nombre: "Ana Karen Ibarra", licencia: "B-7741220", telefono: "55 3390 1188", estado: "disponible" },
];

export const viajesSeed: Viaje[] = [
  {
    id: "v1",
    folio: "RT-2601",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Monterrey",
    salidaIda: "2026-08-12",
    retornoEstimado: "2026-08-16",
    unidadId: "u1",
    operadorId: "o1",
    estado: "en_ruta_vuelta",
    kmRedondo: 1720,
    tarifa: 48500,
    notas: "Retorno con carga de compensación desde Apodaca.",
  },
  {
    id: "v2",
    folio: "RT-2602",
    cliente: "Alimentos La Huerta",
    origen: "Guadalajara",
    destino: "CDMX",
    salidaIda: "2026-08-14",
    retornoEstimado: "2026-08-17",
    unidadId: "u2",
    operadorId: "o2",
    estado: "en_ruta_ida",
    kmRedondo: 1140,
    tarifa: 31200,
  },
  {
    id: "v3",
    folio: "RT-2603",
    cliente: "Distribuidora Peninsular",
    origen: "CDMX",
    destino: "Puebla",
    salidaIda: "2026-08-15",
    retornoEstimado: "2026-08-15",
    unidadId: "u3",
    operadorId: "o3",
    estado: "programado",
    kmRedondo: 270,
    tarifa: 9800,
    notas: "Mismo día, ida y vuelta.",
  },
  {
    id: "v4",
    folio: "RT-2598",
    cliente: "Grupo Ferretero del Norte",
    origen: "CDMX",
    destino: "Querétaro",
    salidaIda: "2026-08-04",
    retornoEstimado: "2026-08-06",
    unidadId: "u6",
    operadorId: "o5",
    estado: "completado",
    kmRedondo: 430,
    tarifa: 14300,
  },
  {
    id: "v5",
    folio: "RT-2599",
    cliente: "Cementos del Bajío",
    origen: "Querétaro",
    destino: "León",
    salidaIda: "2026-08-07",
    retornoEstimado: "2026-08-09",
    unidadId: "u1",
    operadorId: "o1",
    estado: "completado",
    kmRedondo: 380,
    tarifa: 12750,
  },
  {
    id: "v6",
    folio: "RT-2600",
    cliente: "Alimentos La Huerta",
    origen: "CDMX",
    destino: "Veracruz",
    salidaIda: "2026-08-09",
    retornoEstimado: "2026-08-11",
    unidadId: "u5",
    operadorId: "o4",
    estado: "cancelado",
    kmRedondo: 810,
    tarifa: 22400,
    notas: "Cliente reprogramó el embarque.",
  },
];
